kind: pipeline
type: docker
name: resuelve

steps:
- name: test
  image: node:12.22-alpine3.14
  commands: 
  - npm install

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token

- name: publishg
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: vickpalomo/resuelve
    tags: 1.0.0