kind: pipeline
type: docker
name: resuelve

steps:
- name: test
  image: node:12.22-alpine3.14
  commands: 
  - npm install
  - npm test

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: vickpalomo/resuelve
    tags: 1.0.0